## This script contains some essential functions for the individual level PCA analysis and visualization
# These functions use a covariance matrix as the input
# Individual ID and population labels should also be supplied

## PCA #############

library(tidyverse)
library(dplyr)
library(cowplot)
library(RcppCNPy)

cov_matrix_angsd <- as.matrix(read.table("/home/tburris/TGA/angsd_notrans_snps_pca.cov"))
#Matrix is in order 1-222 on each side
#sample_table <- read_table("sample_table_merged_allpop.tsv")

bamlist=read.table("/home/tburris/TGA/bam_list_all.txt")


ind_label_angsd <- bamlist
pop_label_angsd <- meta.data$loc
x_axis <- 1
y_axis <- 2

PCA <- function(cov_matrix_angsd, ind_label_angsd, pop_label_angsd, x_axis, y_axis, show.point=T, show.label=F, show.ellipse=T, show.line=T, alpha=0)
{
  ## This function takes a covariance matrix and performs PCA.
  # cov_matrix: a square covariance matrix generated by most pca softwares
  # ind_label: a vector in the same order and length as cov_matrix; it contains the individual labels of the individuals represented in the covariance matrix
  # pop_label: a vector in the same order and length as cov_matrix; it contains the population labels of the individuals represented in the covariance matrix
  # x_axis: an integer that determines which principal component to plot on the x axis
  # y_axis: an integer that determines which principal component to plot on the y axis
  # show.point: whether to show individual points
  # show.label: whether to show population labels
  # show.ellipse: whether to show population-specific ellipses
  # show.line: whether to show lines connecting population means with each individual point
  # alpha: the transparency of ellipses
  # index_exclude: the indices of individuals to exclude from the analysis, deleted this for now, but code is index_exclude=vector()
  index_include <- ind_label_angsd
  m <- as.matrix(cov_matrix_angsd)
  e <- eigen(m)
  e_value<-e$values
  x_variance<-e_value[x_axis]/sum(e_value)*100
  y_variance<-e_value[y_axis]/sum(e_value)*100
  e <- as.data.frame(e$vectors)
  e <- cbind(ind_label_angsd, pop_label_angsd, e) 
  colnames(e)[3:(dim(e)[1])]<-paste0("PC",1:(dim(e)[1]-2)) ## with the above individuals removed
  colnames(e)[1:2]<-c("individual", "population")
  assign("pca_table", e, .GlobalEnv)
  
  
  #Add era to e dataframe
  e$era <- "Historical"
  e <- e %>% relocate(era, .after=population)
  e[48:111, 3] <- "Contemporary"
  
  #Add location to e dataframe
  e$location <- "Dup"
  e <- e %>% relocate(location, .after=population)
  
  #Add era to e dataframe
  e$era <- "Historical"
  e <- e %>% relocate(era, .after=population)
  e[48:111, 3] <- "Contemporary"
  
  #Add location to e dataframe
  e$location <- "Dup"
  e <- e %>% relocate(location, .after=population)
  
  colnames(e)[3] <- "Location"
  colnames(e)[4] <- "Era"
  
  ggplot(data=e,aes(x=PC1, y=PC2, color=Era, shape=Location)) +
    geom_point(size=4, alpha=0.4) +
    scale_color_manual(values = c("#00BFC4", "#F8766D"), labels = c("Contemporary", "Historical")) +
    theme_classic() +
    theme(
      axis.text.x = element_blank(),
      axis.text.y = element_blank()
    ) +
    xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
    ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) +
    labs(color="Era", shape="Location")
}

PCA(cov_matrix_angsd, ind_label_angsd, pop_label_angsd,x_axis,y_axis)

